---
# vagrant.yml
- hosts: all
  vars:
    packages: "htop redis-server php5-cli php5-curl git python g++ make checkinstall libssl-dev pkg-config build-essential libpq-dev"
    node_version: v0.10.21
    node_build_path: /home/vagrant/node
    eplite_path: /home/vagrant/etherpad-lite
    eplite_version: release/1.3
    eplite_console_path: /home/vagrant/etherpad-lite-console
    eplite_user: etherpad
    eplite_log_path: /var/log/etherpad-lite
  user: vagrant
  sudo: True
  tasks:
  - name: Copy sources.list
    template: src=templates/etc/apt/sources.list.j2 dest=/etc/apt/sources.list owner=root group=root mode=0644

  - name: Install dotdeb.org key
    apt_key: url=http://www.dotdeb.org/dotdeb.gpg state=present

  - name: Update APT package cache
    command: apt-get update

  - name: Install APT packages
    command: apt-get -y install ${packages}

  - name: Checkout node.js
    git: repo=https://github.com/joyent/node 
         dest=${node_build_path}
         version=${node_version}

  - name: Checkout Etherpad Lite
    git: repo=https://github.com/ether/etherpad-lite 
         dest=${eplite_path}
         version=${eplite_version}

  - name: Create the EP Lite User ${eplite_user}
    user: name=${eplite_user} home=${eplite_path} shell=/bin/false state=present

  - name: Build node.js ${node_version}
    raw: cd ${node_build_path} && ./configure --prefix=/usr/local && make && make install

  - name: Copy EP Lite Configuration
    template: src=templates/settings.json.j2 dest=${eplite_path}/settings.json owner=${eplite_user} group=${eplite_user} mode=0644

  - name: Install redis NPM Module
    npm: name=redis path=${eplite_path} state=present

  - name: Install EP Lite Dependencies
    raw: cd ${eplite_path} && sudo bin/installDeps.sh

  - name: Change Owner for EP Lite Repository
    command: chown -R ${eplite_user}:${eplite_user} ${eplite_path}

  - name: Copy EP Lite init.d Script
    template: src=templates/etc/init.d/etherpad-lite.j2 dest=/etc/init.d/etherpad-lite owner=root group=root mode=0755

  - name: Create Log Folder
    file: path=${eplite_log_path} owner=${eplite_user} group=${eplite_user} mode=0750 recurse=yes state=directory
    notify: Restart EP Lite

  - name: Checkout EP Lite Console
    git: repo=https://github.com/0x46616c6b/etherpad-lite-console
         dest=${eplite_console_path}

  - name: Install redis-commander
    npm: name=redis-commander global=yes

  handlers:
    - name: Restart EP Lite
      action: service name=etherpad-lite state=restarted
